<a href="https://colab.research.google.com/github/NishaS1014/Data-Analytics-using-colab/blob/main/day_4%2C5%2C6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s=pd.Series([100,101,102])
print(s)

0    100
1    101
2    102
dtype: int64


In [ ]:
import numpy as np
add=np.array([[[2,4],[6,8]],[[10,12],[14,16]]])
print(add)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [ ]:
import numpy as np
marks=np.array([[89,90],[98,95]])
print(marks)

[[89 90]
 [98 95]]


In [ ]:
import numpy as np
add=np.array([[[2,4],[6,8]],[[10,12],[14,16]]])
print(add)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [ ]:
import pandas as pd
s=pd.Series([100,101,102],
index=["a","b","c"])
print(s)

a    100
b    101
c    102
dtype: int64


In [ ]:
import numpy as np
array=np.array([9,8,7,6,5,4,3,2,1,0])
new_array=array.reshape(5,2)
print(new_array)

[[9 8]
 [7 6]
 [5 4]
 [3 2]
 [1 0]]


In [ ]:
import pandas as pd
content={
    "RegNo":[15001,15002],
    "Year":["1 year", "3 year"],
    "Deportment":["Bcom", "BSc"]
}
df=pd.DataFrame(content)
print(df)

   RegNo    Year Deportment
0  15001  1 year       Bcom
1  15002  3 year        BSc


In [ ]:
import numpy as np
Marks=[91,97,90,94,99]
Avg=np.median(Marks)
print(Avg)

94.0


In [ ]:
import numpy as np

products = ["Highlighter", "Pen", "Water bottle", "Pencil", "Eraser"]
sales = np.array([42,100,67,89,67])
print("Total Sales:", np.sum(sales))        # 365
print("Average Sales:", np.mean(sales))     # 73.0
print("Highest Sales:", np.max(sales))      # 100
print("Lowest Sales:", np.min(sales))       # 42
best_index = np.argmax(sales)
print("Best Selling Product:", products[best_index])  # Pen

Total Sales: 365
Average Sales: 73.0
Highest Sales: 100
Lowest Sales: 42
Best Selling Product: Pen
