<a href="https://colab.research.google.com/github/NishaS1014/Data-Analytics-using-colab/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([99,98,87,90])
print(marks[0])

99


In [ ]:
def calculate_average(a,b,c):
    return(a+b+c)/3

try:
    a=int(input("Enter 1st number:"))
    b=int(input("Enter 2nd number:"))
    c=int(input("Enter 3rd number:"))
    print("Calculate_Avg:",calculate_average(a,b,c))
except ValueError:
    print("Invalid input")

Enter 1st number:45
Enter 2nd number:55
Enter 3rd number:65
Calculate_Avg: 55.0


In [ ]:
import numpy as np
marks=np.array([97,87,90,98,91,93,85,92])
print(marks[0:6])

[97 87 90 98 91 93]


In [ ]:
Marks=[98,90,97,87,78]

Total=sum(Marks)
Avg=Total/5
Max=max(Marks)
Min=min(Marks)

print("Total:",Total)
print("Average:",Avg)
print("Max Value:",Max)
print("Min Value:",Min)

Total: 450
Average: 90.0
Max Value: 98
Min Value: 78


In [ ]:
try:
    num=int(input("Enter the Number:"))
    print(num)
except:
    print("Invalid input")

Enter the Number:gh
Invalid input


In [ ]:
def calculate_percentage(attended, total):
    return (attended / total) * 100

attended = int(input("Enter number of classes attended: "))
total = int(input("Enter total number of classes: "))

percentage = calculate_percentage(attended, total)

print(f"Attendance percentage: {percentage:.2f}%")

if percentage >= 75:
    print(" Eligible for exam.")
else:
    print("Not eligible for exam.")

Enter number of classes attended: 21
Enter total number of classes: 21
Attendance percentage: 100.00%
 Eligible for exam.


In [ ]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [ ]:
import numpy as np
marks=np.array([[89,90],[98,95]])
print(marks)

[[89 90]
 [98 95]]


In [ ]:
import numpy as np
add=np.array([[[2,4],[6,8]],[[10,12],[14,16]]])
print(add)

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]
