<a href="https://colab.research.google.com/github/NishaS1014/Data-Analytics-using-colab/blob/main/Day_1%2C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Mark1 = int(input("Enter Mark 1: "))
Mark2 = int(input("Enter Mark 2: "))
Mark3 = int(input("Enter Mark 3: "))

Total = Mark1 + Mark2 + Mark3
Average = Total/3

print("Total:", Total)
print("Average:", Average)

if Average >= 50:
    print("Pass")
else:
    print("Fail")

Enter Mark 1: 45
Enter Mark 2: 78
Enter Mark 3: 90
Total: 213
Average: 71.0
Pass


In [ ]:
def greet(name):
   print(name)
greet("NANDHU")


NANDHU


In [ ]:
def add(a,b):
    return a+b
result = add(18,25)
print(result)

43


In [ ]:
import numpy as np
arr=np.zeros([4,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.ones([4,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.linspace(1,4,3)
print(arr)


[1.  2.5 4. ]


In [ ]:
import numpy as np
arr=np.arange(1,3)
print(arr)

[1 2]


In [ ]:
import numpy as np
arr=np.eye(4,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
from google.colab import files

uploaded=files.upload()
file=open("customers 30.csv","r")

data=file.read()

print(data)
file.close()

Saving customers 30.csv to customers 30.csv
idex,Customer Id ,First Name,Last Name,Company,City,Country
1,deejjuf8047,andrew,goodman,"""terry",north angel,macao
2,hhtuh47938,alvin,lane,"""yu",lake don,china
3,v574ke949lh,jenna,harding,"""french",rowland,nepal
4,wbjh3892jel,fernando,ford,"""moon",sharp,sudan
5,58djkjiw93m,kara,woods,may lnc,wst devon,uae
6,kk6883bdim,marrisa,gamble,giles LLC,holtfruiyt,palau
7,hgyywkwlmwl,julie,cooley,"""cherry",toddhaven,iran
8,jheemlwi3,lauren,villa,wiley ltd,fransisco,irak
9,8ud9ddkw3,emily,bryant,"""rangel",mecsiko,israel
10,u998ddf,marie,estrada,harvey PLC,japako,gabon
11,3898vnd3,nichole,cao,"""hooper",roblesport,korea
12,7577shhd3,bernard,ritter,"""leonard",east andre,jersey
13,780fmkus,darryI,archer,duffy lnc,west andre,kenya
14,88sgvm,Ryan,li,best-thomas,east andre,turkey
15,383kfmlvofp,vicki,uez,preston-sosa,brad,henry
16,289dnkdowu,sean,townsend,"""yu",toyville,fiji
17,iuwyjdnebu9,sophia,mathis,"""french",kimmouth,sudan
18,uu0480fmhd,helen,po